# Generated by Django 4.2.9 on 2024-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='--', max_length=255),
        ),
    ]
