# Generated by Django 4.2.9 on 2024-01-23 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pending_requests',
            field=models.ManyToManyField(related_name='group_pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
