# Generated by Django 4.2.9 on 2024-01-23 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_pending_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
